Editor:
  DefaultWorldAsset: "Worlds\\PBRTestWorld.yaml"
  DefaultLayout: "Default"
  Layouts:
    - Name: "Default"
      DockSplits:
        - SplitNode: -1
          SplitDir: 0
          SplitRatio: 0.2
        - SplitNode: -1
          SplitDir: 1
          SplitRatio: 0.25
        - SplitNode: -1
          SplitDir: 3
          SplitRatio: 0.3
      Windows:
        - Name: "Viewport"
          DockIndex: -1
        - Name: "Hierarchy"
          DockIndex: 0
        - Name: "Inspector"
          DockIndex: 1
        - Name: "Console"
          DockIndex: 2