Editor:
  DefaultLayout: "Default"
  Windows:
    - Name: "Viewport"
      IsOpen: true
      CameraPosition: [6.759, 8.722, -10.53]
      CameraForward: [-0.2721, -0.2338, 0.9334]
      CameraUp: [0, 1, 0]
      CameraMovementSpeed: 12
      CameraSensitivity: 0.294
      SelectedAspectRatioIndex: 0
      Camera:
        PerspectiveFOV: 60
        OrthographicSize: 10
        NearPlane: 0.1
        FarPlane: 1000
        Aperture: 8
        ShutterSpeed: 125
        Iso: 100
        ProjectionType: 0
    - Name: "Hierarchy"
      IsOpen: true
    - Name: "Inspector"
      IsOpen: true
    - Name: "Console"
      IsOpen: true
  Layouts:
    - Name: "Default"
      DockSplits:
        - SplitNode: -1
          SplitDir: 0
          SplitRatio: 0.2
        - SplitNode: -1
          SplitDir: 1
          SplitRatio: 0.25
        - SplitNode: -1
          SplitDir: 3
          SplitRatio: 0.3
      Windows:
        - Name: "Viewport"
          DockIndex: -1
        - Name: "Hierarchy"
          DockIndex: 0
        - Name: "Inspector"
          DockIndex: 1
        - Name: "Console"
          DockIndex: 2